### ISSUE TITLE
Cannot Start

### ISSUE THREAD

**Issue by Baidu0Big** [rozari0/NezukoBot#14]
Logged
`  File "/usr/lib64/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib64/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "…/NezukoBot/nezuko/__init__.py", line 30, in <module>
    from aiohttp import ClientSession
ModuleNotFoundError: No module named 'aiohttp'`

What can I do?

Thank your nice product!

**Comment by ghost** [comment]
Install requirements first.
`pip3 install -r requirements.txt`

**Comment by Baidu0Big** [comment]
Thanks, I did it. 
But it still not work

error is same

May is because my python is 3.8?

At Log is lib64/python
At install is lib/python

**Comment by ghost** [comment]
> Thanks, I did it. But it still not work
> 
> error is same
> 
> May is because my python is 3.8?
> 
> At Log is lib64/python At install is lib/python

Check your python libs path then.
