### ISSUE TITLE
Can You Help me with this one thing 

### ISSUE THREAD

**Issue by titu3e** [rozari0/NezukoBot#4]
there's an error with quotly it wont work and if i want to change the image when the bot starts which file do i change in i cant find it

**Comment by ghost** [comment]
Quotly working fine for me, Check API URL and Key again.

If you want to change the image, edit [161](https://github.com/titu3e/NezukoBot/blob/dae5a79e90f3ded244aba1494d7025b4ffea86ba/wbb/__main__.py#L161) and [184](https://github.com/titu3e/NezukoBot/blob/dae5a79e90f3ded244aba1494d7025b4ffea86ba/wbb/__main__.py#L184) with your image link.

**Comment by titu3e** [comment]
> Quotly working fine for me, Check API URL and Key again.
> 
> If you want to change the image, edit [161](https://github.com/titu3e/NezukoBot/blob/dae5a79e90f3ded244aba1494d7025b4ffea86ba/wbb/__main__.py#L161) and [184](https://github.com/titu3e/NezukoBot/blob/dae5a79e90f3ded244aba1494d7025b4ffea86ba/wbb/__main__.py#L184) with your image link.

i changed those two but its still showing the same picture

**Comment by titu3e** [comment]
> Quotly working fine for me, Check API URL and Key again.
> 
> If you want to change the image, edit [161](https://github.com/titu3e/NezukoBot/blob/dae5a79e90f3ded244aba1494d7025b4ffea86ba/wbb/__main__.py#L161) and [184](https://github.com/titu3e/NezukoBot/blob/dae5a79e90f3ded244aba1494d7025b4ffea86ba/wbb/__main__.py#L184) with your image link.

I changed the image link but it's showing the same

**Comment by ghost** [comment]
> > Quotly working fine for me, Check API URL and Key again.
> > If you want to change the image, edit [161](https://github.com/titu3e/NezukoBot/blob/dae5a79e90f3ded244aba1494d7025b4ffea86ba/wbb/__main__.py#L161) and [184](https://github.com/titu3e/NezukoBot/blob/dae5a79e90f3ded244aba1494d7025b4ffea86ba/wbb/__main__.py#L184) with your image link.
> 
> I changed the image link but it's showing the same

Change Upstream_repo on config and change deploy link of heroku on README.md. :p
