### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by titu3e** [rozari0/NezukoBot#5]
More Nsfw Features and afk feature

**Comment by ghost** [comment]
Suggest some NSFW features.
And I Don't think I'll add afk feature.

**Comment by titu3e** [comment]
can you add question command like if we user /nezuko whats todays date? it will reply with todays date?

**Comment by ghost** [comment]
@titu3e Enable Chatbot by /chatbot ENABLE.
Isn’t that enough?

**Comment by titu3e** [comment]
> Suggest some NSFW features. And I Don't think I'll add afk feature.

for nsfw like :
- [/neko](tg://bot_command?command=neko): Sends Random SFW Neko source Images.
 - [/feet](tg://bot_command?command=feet): Sends Random Anime Feet Images.
 - [/yuri](tg://bot_command?command=yuri): Sends Random Yuri source Images.
 - [/trap](tg://bot_command?command=trap): Sends Random Trap source Images.
 - [/futanari](tg://bot_command?command=futanari): Sends Random Futanari source Images.
 - [/hololewd](tg://bot_command?command=hololewd): Sends Random Holo Lewds.
 - [/lewdkemo](tg://bot_command?command=lewdkemo): Sends Random Kemo Lewds.
 - [/sologif](tg://bot_command?command=sologif): Sends Random Solo GIFs.
 - [/cumgif](tg://bot_command?command=cumgif): Sends Random Cum GIFs.
 - [/erokemo](tg://bot_command?command=erokemo): Sends Random Ero-Kemo Images.
 - [/lesbian](tg://bot_command?command=lesbian): Sends Random Les Source Images.
 - [/lewdk](tg://bot_command?command=lewdk): Sends Random Kitsune Lewds.
 - [/ngif](tg://bot_command?command=ngif): Sends Random Neko GIFs.
 - [/tickle](tg://bot_command?command=tickle): Sends Random Tickle GIFs.
 - [/lewd](tg://bot_command?command=lewd): Sends Random Lewds.
 - [/feed](tg://bot_command?command=feed): Sends Random Feeding GIFs.
 - [/eroyuri](tg://bot_command?command=eroyuri): Sends Random Ero-Yuri source Images.
 - [/eron](tg://bot_command?command=eron): Sends Random Ero-Neko source Images.
 - [/cum](tg://bot_command?command=cum): Sends Random Cum Images.
 - [/bjgif](tg://bot_command?command=bjgif): Sends Random Blow Job GIFs.
 - [/bj](tg://bot_command?command=bj): Sends Random Blow Job source Images.
 - [/nekonsfw](tg://bot_command?command=nekonsfw): Sends Random NSFW Neko source Images.
 - [/solo](tg://bot_command?command=solo): Sends Random NSFW Neko GIFs.
 - [/kemonomimi](tg://bot_command?command=kemonomimi): Sends Random KemonoMimi source Images.
 - [/avatarlewd](tg://bot_command?command=avatarlewd): Sends Random Avater Lewd Stickers.
 - [/gasm](tg://bot_command?command=gasm): Sends Random Orgasm Stickers.
 - [/poke](tg://bot_command?command=poke): Sends Random Poke GIFs.
 - [/anal](tg://bot_command?command=anal): Sends Random Anal GIFs.
 - [/hentai](tg://bot_command?command=hentai): Sends Random Hentai source Images.
 - [/avatar](tg://bot_command?command=avatar): Sends Random Avatar Stickers.
 - [/erofeet](tg://bot_command?command=erofeet): Sends Random Ero-Feet source Images.
 - [/holo](tg://bot_command?command=holo): Sends Random Holo source Images.
 - [/tits](tg://bot_command?command=tits): Sends Random Tits source Images.
 - [/pussygif](tg://bot_command?command=pussygif): Sends Random Pussy GIFs.
 - [/holoero](tg://bot_command?command=holoero): Sends Random Ero-Holo source Images.
 - [/pussy](tg://bot_command?command=pussy): Sends Random Pussy source Images.
 - [/hentaigif](tg://bot_command?command=hentaigif): Sends Random Hentai GIFs.
 - [/classic](tg://bot_command?command=classic): Sends Random Classic Hentai GIFs.
 - [/kuni](tg://bot_command?command=kuni): Sends Random Pussy Lick GIFs.
 - [/waifu](tg://bot_command?command=waifu): Sends Random Waifu Stickers.
 - [/kiss](tg://bot_command?command=kiss): Sends Random Kissing GIFs.
 - [/femdom](tg://bot_command?command=femdom): Sends Random Femdom source Images.
 - [/cuddle](tg://bot_command?command=cuddle): Sends Random Cuddle GIFs.
 - [/erok](tg://bot_command?command=erok): Sends Random Ero-Kitsune source Images.
 - [/foxgirl](tg://bot_command?command=foxgirl): Sends Random FoxGirl source Images.
 - [/titsgif](tg://bot_command?command=titsgif): Sends Random Tits GIFs.
 - [/ero](tg://bot_command?command=ero): Sends Random Ero source Images.
 - [/smug](tg://bot_command?command=smug): Sends Random Smug GIFs.
 - [/baka](tg://bot_command?command=baka): Sends Random Baka Shout GIFs.
 - [/dva](tg://bot_command?command=dva): Sends Random [D.VA](https://d.va/) source Images.

**Comment by ghost** [comment]
@titu3e Noted. :3

**Comment by ghost** [comment]
Well, Starting work on new bot from scratch. So closing all old issue.
